/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_28Mei2024;

/**
 *
 * @author AULIA SYFA
 */
public class fromstudenrecoard extends javax.swing.JFrame {

    /**
     * Creates new form fromstudenrecoard
     */
    public fromstudenrecoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMathGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnglisGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScienceGrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAvarage = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 50, 16);
        getContentPane().add(txtName);
        txtName.setBounds(110, 30, 160, 20);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 60, 16);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(110, 60, 160, 22);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 21, 16);

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        getContentPane().add(txtAge);
        txtAge.setBounds(110, 90, 160, 22);

        jLabel4.setText("MathGrade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 59, 20);

        txtMathGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMathGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(110, 120, 160, 20);

        jLabel5.setText("EnglishGrade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 16);
        getContentPane().add(txtEnglisGrade);
        txtEnglisGrade.setBounds(110, 150, 160, 22);

        jLabel6.setText("ScienceGrade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 80, 16);
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(110, 180, 160, 22);

        jLabel7.setText("Avarage");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 240, 50, 16);
        getContentPane().add(txtAvarage);
        txtAvarage.setBounds(110, 240, 160, 20);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(10, 210, 330, 20);

        setSize(new java.awt.Dimension(372, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        pbo_26Maret2024.StudentRecord student = new pbo_26Maret2024.StudentRecord();
        student.setName(txtName.getText());
        student.setAddress(txtAddress.getText());
        student.setAge(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMathGrade.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglisGrade.getText()));
         student.setScienceGrade(Double.parseDouble(txtScienceGrade.getText()));
         ///
       txtAvarage.setText(student.getAverage()+"");
         ///
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtMathGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathGradeActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtAgeActionPerformed

    /**
     * @param argts the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromstudenrecoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromstudenrecoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromstudenrecoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromstudenrecoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromstudenrecoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAvarage;
    private javax.swing.JTextField txtEnglisGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScienceGrade;
    // End of variables declaration//GEN-END:variables
}
